### ISSUE TITLE
What options can I pass to config.json?

### ISSUE THREAD

**Issue by unr** [thecreazy/siteaudit#1]
I don't see any guidance on what I can possibly change in the config file.

Is there a way to turn off things like PWA, if we don't care about that rating?

can we do different resolutions, instead of just mobile?

**Comment by thecreazy** [comment]
Hi, i will a add a complete example of the config.json 👍  thx for the point.

**Comment by asmahler** [comment]
Let me know if you need any help with this!

**Comment by thecreazy** [comment]
i'v started adding base config.json config in the readme
