### ISSUE TITLE
[question] Site login

### ISSUE THREAD

**Issue by jotavejv** [thecreazy/siteaudit#5]
How can I use it with site that need a login?
Thanks.

**Comment by thecreazy** [comment]
basic auth authentication ? or a complete login form ?

**Comment by jotavejv** [comment]
basic authentication, how can I pass the credentials? user and password.
I didn't find any example in the documentation.

**Comment by thecreazy** [comment]
You can use a special URL format, like this: http://username:password@example.com/ -- this sends the credentials in the standard HTTP "Authorization" header.

This is not a siteaudit feature it’s the basic http/s protocol
